#インストールされているバージョンによって末尾の数字調整
runtime: python312

# 下記は 設定用ディレクトリ.wsgi:application のように記述
entrypoint: gunicorn -b :$PORT FibRestApiProject.wsgi

# 下記はhttpでアクセスがあった際、httpsにリダイレクトするための記述
handlers:
- url: /static
  static_dir: static/

env_variables:
  DJANGO_SETTINGS_MODULE: FibRestApiProject.settings
  APPENGINE_URL: https://fibapp.uc.r.appspot.com
  # http://fibapp-427213.an.r.appspot.com